### Normal request
POST http://localhost:3003/exercises
Content-Type: application/json

{
    "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
    "target": 2.5
}

### Missing target value
POST http://localhost:3003/exercises
Content-Type: application/json

{
    "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5]
}

### Missing "daily_exercises" value
POST http://localhost:3003/exercises
Content-Type: application/json

{
    "daily_exercises": [],
    "target": 1
}