GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Create a blog with userId",
    "author": "Sergei Kolygin",
    "url": "salainen",
    "likes": "456",
    "userId": "6313464143df4a0893339e35"
}

###
PUT http://localhost:3003/api/blogs/630f3f96812de15d401202bf
content-type: application/json

{
  "title": "How to live",
  "author": "Andrew",
  "url": "qwqw.aase.er",
  "likes": 10,
  "id": "630f3f96812de15d401202bf"
}